[project]
name = "basic-components"
version = "0.1.0"
description = ""
authors = [
    {name = "phernandez", email = "phernandez@basicmachines.co"},
]
readme = "README.md"
requires-python = ">=3.10"

packages = ["components", "docs"]
dependencies = [
    "fastapi[standard]>=0.115.4",
    "jinjax[whitenoise]>=0.47",
    "pyright>=1.1.385",
    "pytest-playwright>=0.5.2",
    "pytest>=8.3.3",
    "starlette-wtf>=0.4.5",
    "uvicorn>=0.32.0",
    "wtforms>=3.2.1",
    "jinja2>=3.1.3",
    "python-frontmatter>=1.1.0", # For markdown metadata
    "pygments>=2.17.2", # For code highlighting
    "loguru>=0.7.2",
    "pydantic>=2.9.2",
    "pydantic-settings>=2.6.0",
    "arel>=0.3.0",
    "websockets>=13.1",
    "markdown-it-py[plugins]>=3.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["components"]
