[project]
name = "basic-components"
version = "0.1.0"
description = ""
authors = [
    {name = "phernandez", email = "phernandez@basicmachines.co"},
]
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
