site_name: Basic Components
repo_url: https://github.com/basicmachines-co/basic-components

# left navbar links and routes
nav:
  - Getting Started:
      - Introduction: /docs/introduction
      - Installation: /docs/installation
      - JinjaX: /docs/jinajx
      - htmx: /docs/htmx
      - Dark mode: /docs/dark_mode
  - Installation:
      - Fastapi: /docs/fastapi
      - Copy/Paste: /docs/copy_paste
      - Vendoring: /docs/vendoring
  - Components:
      - Accordion: /components/accordion
      - Alert: /components/alert
      - Badge: /components/badge
      - Button: /components/button
      - Card: /components/card
      - Checkbox: /components/checkbox
      - Dialog: /components/dialog
      - Dropdown Menu: /components/dropdown_menu
      - Form: /components/form
      - Input: /components/input
      - Label: /components/label
      - Link: /components/link
      - Mode Toggle: /components/mode_toggle
      - Popover: /components/popover
      - Radio Group: /components/radio_group
      - Select: /components/select
      - Sheet: /components/sheet
      - Table: /components/table
      - Textarea: /components/textarea
      - Toast: /components/toast
      - WTForm: /components/wtform
  - Examples:
      - Login: /examples/login
      - Dashboard: /examples/dashboard
