site_name: Basic Components

repo_url: https://github.com/basicmachines-co/basic-components

theme:
  name: material
  font:
    text: Inter
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - include-markdown
  - macros:
      include_dir: docs/components

extra:
  preview_url: !ENV [PREVIEW_URL, "https://basic-components.onrender.com"]

extra_css:
  - assets/styles/custom.css

extra_javascript:
  - javascript/sync-theme.js
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Installation:
      - Fastapi: installation/fastapi.md
  - Usage:
      - Copy/Paste: usage/copy_paste.md
      - Vendoring: usage/vendoring.md
  - Components:
      - Accordion: components/accordion.md
      - Alert: components/alert.md
      - Badge: components/badge.md
      - Button: components/button.md
      - Card: components/card.md
      - Checkbox: components/checkbox.md
      - Dialog: components/dialog.md
      - DropdownMenu: components/dropdown_menu.md
      - Form: components/form.md
      - Input: components/input.md
      - Label: components/label.md
      - Link: components/link.md
      - ModeToggle: components/mode_toggle.md
      - Popover: components/popover.md
      - RadioGroup: components/radio_group.md
      - Select: components/select.md
      - Sheet: components/sheet.md
      - Table: components/table.md
      - TextArea: components/text_area.md
      - Toast: components/toast.md
      - WTForm: components/wtform.md
