site_name: Basic Components
theme:
  name: material
  font:
    text: Inter
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - include-markdown

extra_javascript:
  - javascript/sync-theme.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Components:
      - Button: components/button.md
      - Card: components/card.md
