site_name: Basic Components
theme:
  name: material
nav:
  - Home: index.md
  - Components:
      - Button: components/button.md
      - Card: components/card.md
plugins:
  - search

extra_javascript:
  - https://unpkg.com/htmx.org@1.9.2
  - https://unpkg.com/alpinejs@3.12.0/dist/cdn.min.js

extra_css:
  - dist/output.css
